name: autocommit-robot

on:
  schedule:
    - cron: "5,8,18,28,38,48,58 0 * * *"
    - cron: "8 1 * * *"
  workflow_dispatch:

jobs:
  bots:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: Asia/Shanghai
      ACCOUNT_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCOUNT_TOKEN }}

      - name: "Set node"
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: "Install"
        run: npm install --no-audit

      - name: "Generate version and tag"
        id: tag-version
        run: |
          VERSION="v$(date +'%Y.%m.%d')"
          TODAY_TAGS=$(git tag -l "${VERSION}*" | wc -l)
          NEW_TAG="${VERSION}.${TODAY_TAGS}"
          echo "new_tag=${NEW_TAG}" >> $GITHUB_OUTPUT

      - name: "Generate commit message"
        id: commit-message
        run: |
          EMOJIS=(
              "🤖" "💻" "⌨️" "🖥️" "🖲️" "🎮" "🕹️" "📱" "☎️" "⌚️" "⚡️" "💡" "🔌" "🔋"
              "🎨" "🎭" "🎪" "🎠" "🎬" "📸" "🎥" "🎙️" "🎧" "🎹" "🎼" "🎵" "🎶" "🖼️"
              "✨" "💫" "🌟" "⭐️" "✴️" "🔮" "🪄" "🎇" "🎆" "🌠" "🌌" "👾" "🛸" "🌍"
              "🔧" "🔨" "⚒️" "🛠️" "⚙️" "🔩" "⛓️" "📐" "📏" "✂️" "🗜️" "📌" "🔍" "💎"
              "🎯" "🎪" "🏆" "🏅" "🎖️" "🔝" "📈" "💯" "🎳" "🎲" "🎱" "🧩" "♟️" "🎰"
              "🚀" "✈️" "🛩️" "🛰️" "🌈" "🌊" "💨" "🌪️" "⚡️" "🔥" "💥" "🎢" "🎡" "🎪"
              "💡" "💭" "💫" "🧠" "🎉" "🎊" "🌟" "💪" "📚" "🔬" "🧪" "🧬" "🔭" "⚗️"
              "👽" "🤖" "👾" "🛸" "🌌" "🌠" "🚀" "💫" "✨" "🔮" "🎆" "🎇" "⭐️" "🌟"
              "🏗️" "🏢" "🏭" "🏛️" "🏘️" "🏰" "🗼" "🗽" "🗿" "🎪" "🌉" "🌇" "🌆" "🌃"
              "📡" "📱" "📟" "📠" "🔌" "🔋" "💻" "🖥️" "⌨️" "🖱️" "🖨️" "🖲️" "📼" "💽"
          )
          RANDOM_EMOJI=${EMOJIS[$RANDOM % ${#EMOJIS[@]}]}

          DATETIME=$(date '+%Y-%m-%d %H:%M:%S')

          DESCRIPTIONS=(
            "Generated new robot avatar with unique characteristics"
            "Created an innovative robot design with special features"
            "Daily robot collection updated with fresh perspective"
            "Added a distinctive mechanical companion to the gallery"
            "Synthesized a new artificial intelligence visualization"
            "Crafted a one-of-a-kind robotic entity"
            "Introduced a new member to our robot family"
            "Enhanced the collection with a modern robot design"
            "Automated art generation completed successfully"
            "New digital persona has been materialized"
            "Expanded robot archive with latest creation"
            "Designed and implemented new robot variation"
            "Revolutionary robot concept brought to life"
            "Artificial entity visualization completed"
            "Generated unique mechanical character design"
            "Advanced robot prototype visualization added"
            "Innovative machine learning visualization created"
            "Artistic interpretation of AI consciousness"
            "Robotic expression system newly generated"
            "Cutting-edge robot design implementation"
            "Futuristic mechanical entity materialized"
            "Next-generation robot concept realized"
            "Dynamic robot personality generated"
            "Artificial being visualization completed"
            "Breakthrough in robot avatar design"
            "Revolutionary mechanical form created"
            "Advanced AI visualization system output"
            "Experimental robot design materialized"
            "State-of-the-art robot rendering complete"
            "Innovative mechanical life form designed"
          )
          RANDOM_DESC=${DESCRIPTIONS[$RANDOM % ${#DESCRIPTIONS[@]}]}

          ACTIONS=("feat" "update" "create" "generate" "implement" "design" "craft" "develop")
          RANDOM_ACTION=${ACTIONS[$RANDOM % ${#ACTIONS[@]}]}

          SCOPES=("robot" "ai" "avatar" "design" "generator" "collection")
          RANDOM_SCOPE=${SCOPES[$RANDOM % ${#SCOPES[@]}]}

          MESSAGE="${RANDOM_EMOJI} ${RANDOM_ACTION}(${RANDOM_SCOPE}): ${RANDOM_DESC} [${DATETIME}] - Tag: ${{ steps.tag-version.outputs.new_tag }}"
          echo "message=${MESSAGE}" >> $GITHUB_OUTPUT

      - name: "Run bash"
        run: |
          mkdir -p pictures
          node scripts/commit.js
          date > pictures/timestamp.txt

      - name: "Commit and Push"
        run: |
          git config --local user.email "xuqssq@gmail.com"
          git config --local user.name "Qian"
          git add pictures/*
          git commit -m "${{ steps.commit-message.outputs.message }}" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}

      - name: "Create and push tag"
        if: success()
        run: |
          git tag ${{ steps.tag-version.outputs.new_tag }}
          git push origin ${{ steps.tag-version.outputs.new_tag }}
